# site settings
title: Fons Minervae
subtitle: jwrg's homepage and blog
email: jwrg@uvic.ca
description: Jim Galloway
baseurl: "" # the subpath of your site, e.g. /blog
url: https://jwrg.github.io # the base hostname & protocol for your site
author: jwrg
street_address: 
city: Vancouver
state: BC
zip_code: 
country: Canada
phone: 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/jwrg
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
