# site settings
title: jwrg's homepage and blog
subtitle: subtitle
email: jwrg@uvic.ca
description: description goes here
baseurl: "" # the subpath of your site, e.g. /blog
url: https://jwrg.github.io # the base hostname & protocol for your site
author: jwrg
street_address: 
city: 
state: 
zip_code: 
country: 
phone: 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 3

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
